# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

# Use a Microsoft-hosted agent for simplicity (if your pool isn't configured properly)
# If you want to continue with 'ronaldo', you can keep it as is
pool: 
  name: ronaldo  # Keep using the 'ronaldo' pool if it's working fine with Maven

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'  # Ensure the path to the pom.xml is correct
    mavenOptions: '-Xmx3072m'  # Adjust memory for Maven build if needed
    javaHomeOption: 'JDKVersion'  # Use JDK installed on the agent
    jdkVersionOption: '1.11'  # Set JDK version to 1.11 (ensure this is available in your agent)
    jdkArchitectureOption: 'x64'  # Ensure 64-bit architecture
    publishJUnitResults: true  # Enable publishing of JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Correct path to test results
    goals: 'package'  # Default Maven goal for building the project
