# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main  # Triggers the pipeline on commits to the main branch.

pool:
  name: ronaldo  # Use the ronaldo agent pool
  demands:
    - maven  # Ensure Maven is installed on the agent

steps:
# Debug: Output all environment variables to check available variables
- script: |
    echo "Available Environment Variables:"
    printenv
  displayName: 'Debug: Output Environment Variables'

# Checkout the code from the repository
- task: Checkout@1
  displayName: 'Checkout Code'

# Build the project using Maven
- task: Maven@3
  displayName: 'Build and Package with Maven'
  inputs:
    mavenPomFile: 'pom.xml'  # Path to the Maven POM file.
    mavenOptions: '-Xmx3072m'  # JVM options for Maven.
    javaHomeOption: 'JDKVersion'  # Use JDK installed on the agent.
    jdkVersionOption: '1.11'  # Specify JDK version (Java 11).
    jdkArchitectureOption: 'x64'  # Specify JDK architecture (64-bit).
    publishJUnitResults: true  # Publish JUnit test results.
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Path to test results.
    goals: 'package'  # Maven goal to execute.

# Publish the build artifacts (optional)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathToPublish: 'target'  # Directory to publish (e.g., Maven output folder).
    artifactName: 'drop'  # Name of the artifact.
    publishLocation: 'Container'
